=== darambaris/CurriculoLattes/xsd/curriculo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- *************************************************************************************
Nome: Jéssika Darambaris Oliveira No: 7961026
Nome: Vitor P. Ribeiro No: 7961005

Arquivo: curriculo.xsd
Descricao: XMLSchema responsável por validar os arquivos XMLs encontrados na pasta XML.
************************************************************************************** -->
<xs:schema targetNamespace="http://www.multimidia-lattes.com/lattes" xmlns="http://www.multimidia-lattes.com/lattes" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- elemento raiz -->
	<xs:element name="CURRICULO">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="NOME" type="xs:string" />
				<xs:element name="AVATAR" type="complex_photo" />
				<xs:element name="RESUMO-CV" type="xs:string" />
				<xs:element name="INFORMACOES-PESSOAIS" type="complex_info_pessoal"/>
				<xs:element name="FORMACAO-ACADEMICA" type="complex_academica"/>
				<xs:element name="PUBLICACOES" type="complex_publicacoes"/>
				<xs:element name="ORIENTACOES" type="complex_orientacoes"/>
			</xs:sequence>	
			<xs:attribute name="id" type="xs:string" fixed="curriculo" use="required"/>
		</xs:complexType>	
	</xs:element>
	
<!-- ***************** tipos complexos ********************************** -->	

<!-- filhos do elemento CURRICULO -->
	<xs:complexType name="complex_photo">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="src" type="url_photo"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="complex_info_pessoal">
		<xs:sequence>
			<xs:element name="IDENTIFICACAO" type="complex_identificacao"/>
			<xs:element name="ENDERECO" type="complex_endereco"/>
		</xs:sequence>
	</xs:complexType>	
	
	<xs:complexType name="complex_academica">	
		<xs:sequence>
			<xs:element name="GRADUACAO" type="complex_type_academica"/>
			<xs:element name="ESPECIALIZACAO" minOccurs="0" maxOccurs="5" type="complex_type_academica"/>
			<xs:element name="MESTRADO" type="complex_type_academica"/>
			<xs:element name="DOUTORADO" type="complex_type_academica"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="complex_publicacoes">	
		<xs:sequence>
			<xs:element name="PUBLICACAO" minOccurs="0" maxOccurs="100" type="complex_publicacao"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="complex_orientacoes">	
		<xs:sequence>
			<xs:element name="ORIENTACAO" minOccurs="0" maxOccurs="100" type="complex_orientacao"/>
		</xs:sequence>
	</xs:complexType>
		
<!-- filhos do elemento INFORMACOES-PESSOAIS -->
	<xs:complexType name="complex_identificacao">
		<xs:sequence>
			<xs:element name="NOME" type="xs:string"/>
			<xs:element name="CITACAO-BIBLIOGRAFICA" minOccurs="0" maxOccurs="30" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="complex_endereco">
		<xs:sequence>
			<xs:element name="ENDERECO-PROFISSIONAL" type="complex_type_end"/>
			<xs:element name="ENDERECO-PESSOAL" type="complex_type_end"/>
		</xs:sequence>
		<xs:attribute name="preferencia" use="required" type="type_endereco" />
	</xs:complexType>

	<!-- filhos do elemento FORMACAO-ACADEMICA -->
	<xs:complexType name="complex_type_academica">
		<xs:sequence>
			<xs:sequence>
				<xs:element name="TITULO" type="xs:string"/>
				<xs:element name="INSTITUICAO" type="attrib_instituicao"/>
				<xs:choice minOccurs="0"> <!-- OPCIONAL --> 
					<xs:element name="TITULO-TCC" type="xs:string"/>
					<xs:element name="TITULO-TESE" type="xs:string"/>
				</xs:choice>
				<xs:element name="ORIENTADOR" type="xs:string"/>
				<xs:element name="DURACAO" type="complex_duracao"/>
			</xs:sequence>	
		</xs:sequence>
		<xs:attribute name="status" type="type_status"/>
	</xs:complexType>	
	
	<!-- filhos do elemento PUBLICACAO -->
	<xs:complexType name="complex_publicacao">
		<xs:sequence>
			<xs:element name="AUTOR" maxOccurs="20" type="xs:string" />
			<xs:element name="TITULO" type="xs:string" />
			<xs:element name="IN" type="xs:string" minOccurs="0" />
			<xs:element name="TITULO-PUBLICACAO" type="xs:string" />
			<xs:element name="ANO" type="type_ano" />
		</xs:sequence>
		<xs:attribute name="tipo" type="type_publicacao"/>
	</xs:complexType>
	
	<!-- filhos do elemento ORIENTACAO -->
	<xs:complexType name="complex_orientacao">
		<xs:sequence>
			<xs:element name="ALUNO" type="xs:string" />
			<xs:element name="TITULO" type="xs:string" />
			<xs:element name="ANO" type="type_ano" />
			<xs:element name="INSTITUICAO" type="attrib_instituicao" />
		</xs:sequence>
		<xs:attribute name="tipo" type="type_orientacao"/>
		<xs:attribute name="status" type="type_status"/>
	</xs:complexType>
	
	<!-- filhos dos elementos ENDERECO-PROFISSIONAL e ENDERECO-PESSOAL -->
	<xs:complexType name="complex_type_end">
		<xs:sequence>
			<!-- para facilitar análise foi considerado que a instuição e órgão 
				são elementos opcionais --> 
			<xs:element name="INSTITUICAO" minOccurs="0" type="attrib_instituicao"/>
			<xs:element name="ORGAO" minOccurs="0" type="attrib_orgao"/>
			<xs:element name="LOGRADOURO-COMPLETO" type="xs:string"/>
			<xs:element name="CEP" type="type_CEP"/>
			<xs:element name="BAIRRO" type="xs:string"/>
			<xs:element name="CIDADE" type="xs:string"/>
			<xs:element name="PAIS" type="type_pais"/>
			<xs:element name="TELEFONE" type="complex_telefone"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- filhos do elemento DURACAO -->
	<xs:complexType name="complex_duracao">
		<xs:sequence>
			<xs:element name="INICIO" type="type_ano"/>
			<xs:element name="CONCLUSAO" type="type_ano"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- filhos do elemento TELEFONE -->
	<xs:complexType name="complex_telefone">
		<xs:sequence>
			<xs:element name="DDD" type="type_ddd"/>
			<xs:element name="NUMERO" type="type_numero"/>
		</xs:sequence>
	</xs:complexType>
	
<!-- elementos texto com atributos --> 	
	<xs:complexType name="attrib_instituicao">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="codigo" use="required" type="type_id"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>	
	<xs:complexType name="attrib_orgao">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="codigo" use="required" type="type_id"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>	
	
<!-- tipos de variáveis -->	
	<xs:simpleType name="url_photo">
		<xs:restriction base="xs:string">
			<xs:pattern value="./img/[A-Za-z0-9]{1,20}.(jpg|png|bmp)"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="type_endereco">
		<xs:restriction base="xs:string">
			<!-- são opções que definem que endereços vão aparecer na página --> 
			<xs:pattern value="(profissional|pessoal|ambos)"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="type_status">
		<xs:restriction base="xs:string">
			<xs:pattern value="(andamento|concluido)"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="type_ano">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1900"/>
			<xs:maxInclusive value="2015"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="type_publicacao">
		<xs:restriction base="xs:string">
			<xs:pattern value="(livro|capitulo_livro|artigo|trabalho)"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="type_orientacao">
		<xs:restriction base="xs:string">
			<xs:pattern value="(mestrado|doutorado|iniciacao)"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="type_pais">
		<xs:restriction base="xs:string">
			<!-- para facilitar a formatação do cep e telefone, 
			foi cnosiderado apenas o Brasil -->
			<xs:pattern value="(Brasil|BR|BRASIL)"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="type_CEP">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{5}-\d{3}"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="type_ddd">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="11"/>
			<xs:maxInclusive value="99"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="type_numero">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{4}-\d{4}"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="type_id">
	<xs:restriction base="xs:string">
		<xs:pattern value="\d{12}"/>
	</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== darambaris/CurriculoLattes/xml/rgoularte.xml
<?xml-stylesheet type="text/xsl" href="./xsl/inf_pessoal.xsl"?>
<!-- *************************************************************************************
Nome: Jéssika Darambaris Oliveira No: 7961026
Nome: Vitor P. Ribeiro No: 7961005

Arquivo: rgoularte.xml
Descricao: XML baseado nas informações do Currículo Lattes do prof. Rudinei Goularte
************************************************************************************** -->
<?xml-stylesheet type="text/xsl" href="./xsl/academica.xsl"?>
<?xml-stylesheet type="text/xsl" href="./xsl/orientacoes.xsl"?>
<?xml-stylesheet type="text/xsl" href="./xsl/publicacoes.xsl"?>
<CURRICULO id="curriculo" xmlns="http://www.multimidia-lattes.com/lattes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.multimidia-lattes.com/lattes ./xsd/curriculo.xsd">	
	<NOME>Rudinei Goularte</NOME>
	<AVATAR src="./img/avatar.jpg"/>
	<RESUMO-CV>
		Possui graduação em Ciências da Computação pela Universidade Federal de Mato Grosso do Sul (1995). Possui mestrado (1998), doutorado (2003) e livre-docência (2011) pela Universidade de São Paulo [São Carlos], todos em Ciência da Computação. Atualmente é professor associado do ICMC/USP em regime de dedicação integral à docência e à pesquisa e orientador pleno de mestrado e doutorado. Atua como consultor ad hoc da Fundação de Amparo à Pesquisa do Estado de São Paulo (FAPESP) e do Conselho Nacional de Desenvolvimento Científico e Tecnológico (CNPq). Desenvolve pesquisa em Multimídia nas linhas: codificação de vídeo digital, vídeo 3D, recuperação baseada em conteúdo, personalização de conteúdo e tv interativa.
	</RESUMO-CV>
	<INFORMACOES-PESSOAIS>
		<IDENTIFICACAO>
			<NOME>Rudinei Goularte</NOME>
			<CITACAO-BIBLIOGRAFICA>GOULARTE, R</CITACAO-BIBLIOGRAFICA>	
			<CITACAO-BIBLIOGRAFICA>Goularte, Rudinei</CITACAO-BIBLIOGRAFICA>
		</IDENTIFICACAO>
		<!-- indica qual endereço deve aparecer na página (profissinal, pessoal ou ambos) -->
		<ENDERECO preferencia="profissional">
			<ENDERECO-PROFISSIONAL>
				<INSTITUICAO codigo="006700000002">Universidade de São Paulo</INSTITUICAO>
				<ORGAO codigo="006742000000">Instituto de Ciências Matemáticas e de Computação</ORGAO>
				<LOGRADOURO-COMPLETO>Av. Trabalhador São-carlense, 400</LOGRADOURO-COMPLETO>
				<CEP>13560-970</CEP>
				<BAIRRO>Centro</BAIRRO>
				<CIDADE>São Carlos</CIDADE>
				<PAIS>Brasil</PAIS>
				<TELEFONE>
					<DDD>16</DDD>
					<NUMERO>3373-6623</NUMERO>
				</TELEFONE>
			</ENDERECO-PROFISSIONAL>	
			<ENDERECO-PESSOAL>
				<LOGRADOURO-COMPLETO>R. 28 de Setembro, 2350, ap 54</LOGRADOURO-COMPLETO>
				<CEP>13560-270</CEP>
				<BAIRRO>Centro</BAIRRO>
				<CIDADE>São Carlos</CIDADE>
				<PAIS>Brasil</PAIS>
				<TELEFONE>
					<DDD>16</DDD>
					<NUMERO>3412-5678</NUMERO>
				</TELEFONE>
			</ENDERECO-PESSOAL>	
		</ENDERECO>
	</INFORMACOES-PESSOAIS>	
	<FORMACAO-ACADEMICA>
		<GRADUACAO status="concluido">
			<TITULO>Graduação em Bacharel Em Ciência da Computação. </TITULO>
			<INSTITUICAO codigo="006742000000">Universidade Federal de Mato Grosso do Sul. </INSTITUICAO>
			<TITULO-TCC> Não informado. </TITULO-TCC>
			<ORIENTADOR> Não informado. </ORIENTADOR>
			<DURACAO>
				<INICIO>1992</INICIO>
				<CONCLUSAO>1995</CONCLUSAO>
			</DURACAO>	
		</GRADUACAO>
		<MESTRADO status="concluido">
			<TITULO> Mestrado em Ciências de Computação e Matemática Computacional.  </TITULO>
			<INSTITUICAO codigo="006742000000"> Instituto de Ciências Matemáticas e de Computação Usp São Carlos </INSTITUICAO>
			<TITULO-TESE> Utilização de Metadados no Gerenciamento de Acesso a Servidores Multimídia </TITULO-TESE>
			<ORIENTADOR>Edson dos Santos Moreira. </ORIENTADOR>
			<DURACAO>
				<INICIO>1996</INICIO>
				<CONCLUSAO>1998</CONCLUSAO>
			</DURACAO>	
		</MESTRADO>
		<DOUTORADO status="concluido">
			<TITULO> Doutorado em Ciências de Computação e Matemática Computacional. </TITULO>
			<INSTITUICAO codigo="006742000000"> Instituto de Ciências Matemáticas e de Computação Usp São Carlos </INSTITUICAO>
			<TITULO-TESE> Personalização e adaptação de conteúdo baseadas em contexto para TV Interativa. </TITULO-TESE>
			<ORIENTADOR>Edson dos Santos Moreira. </ORIENTADOR>
			<DURACAO>
				<INICIO>1999</INICIO>
				<CONCLUSAO>2003</CONCLUSAO>
			</DURACAO>	
		</DOUTORADO>
	</FORMACAO-ACADEMICA>	
	<PUBLICACOES>
		<PUBLICACAO tipo="artigo">
			<AUTOR>MOREIRA, E. D. S.</AUTOR>
			<AUTOR>GOULARTE, R.</AUTOR>
			<TITULO>Managing Access to a Video Server Through a Metadata Base</TITULO>
			<TITULO-PUBLICACAO>International Journal of Computers and Applications</TITULO-PUBLICACAO>
			<ANO>2001</ANO>
		</PUBLICACAO>
		<PUBLICACAO tipo="artigo">
			<AUTOR>SANTOS JÚNIOR, J. B.</AUTOR>
			<AUTOR>GOULARTE, R.</AUTOR>
			<AUTOR>MOREIRA, E. D. S.</AUTOR>
			<AUTOR>FARIA, G. B.</AUTOR>
			<TITULO>The Modelling of Structured Context-Aware Interactive Environments</TITULO>
			<TITULO-PUBLICACAO>Journal of Integrated Design and Process Science</TITULO-PUBLICACAO>
			<ANO>2001</ANO>
		</PUBLICACAO>
		<PUBLICACAO tipo="artigo">
			<AUTOR>PISSIOLI, M.</AUTOR>
			<AUTOR>MOREIRA, E. D. S.</AUTOR>
			<AUTOR>GOULARTE, R.</AUTOR>
			<TITULO>Experiments for Analysis of Video Transmission via ATM</TITULO>
			<TITULO-PUBLICACAO>Journal of Computer Science and Technology (La Plata)</TITULO-PUBLICACAO>
			<ANO>2002</ANO>
		</PUBLICACAO>
		<PUBLICACAO tipo="artigo">
			<AUTOR>CASTRO, M. A. S.</AUTOR>
			<AUTOR>GOULARTE, R.</AUTOR>
			<AUTOR>REAMI, E. R.</AUTOR>
			<AUTOR>MOREIRA, E. D. S.</AUTOR>
			<TITULO>Infra-Estrutura De Suporte A Editoração De Material Didático Utilizando Multimídia</TITULO>
			<TITULO-PUBLICACAO>Revista Brasileira de Informática na Educação</TITULO-PUBLICACAO>
			<ANO>1997</ANO>
		</PUBLICACAO>
		<PUBLICACAO tipo="artigo">
			<AUTOR>GOULARTE, R.</AUTOR>
			<AUTOR>PIMENTEL, Maria da Graca Campos</AUTOR>
			<AUTOR>MOREIRA, E. D. S.</AUTOR>
			<TITULO>Context-Aware Support in Structured Documents for Interactive-TV</TITULO>
			<TITULO-PUBLICACAO>Multimedia Systems</TITULO-PUBLICACAO>
			<ANO>2006</ANO>
		</PUBLICACAO>
		<PUBLICACAO tipo="artigo">
			<AUTOR>CATTELAN, R. G.</AUTOR>
			<AUTOR>Teixeira, Cesar</AUTOR>
			<AUTOR>GOULARTE, R.</AUTOR>
			<AUTOR>PIMENTEL, Maria da Graca Campos</AUTOR>
			<TITULO>Watch-and-comment as a paradigm toward ubiquitous interactive video editing</TITULO>
			<TITULO-PUBLICACAO>ACM Transactions on Multimedia Computing Communications and Applications</TITULO-PUBLICACAO>
			<ANO>2008</ANO>
		</PUBLICACAO>
		<PUBLICACAO tipo="artigo">
			<AUTOR>MANZATO, M. G.</AUTOR>
			<AUTOR>MACEDO, A. A.</AUTOR>
			<AUTOR>GOULARTE, R.</AUTOR>
			<TITULO>Evaluation of Video News Classification Techniques for Automatic Content Personalization</TITULO>
			<TITULO-PUBLICACAO>International Journal of Advanced Media and Communication</TITULO-PUBLICACAO>
			<ANO>2009</ANO>
		</PUBLICACAO>
		<PUBLICACAO tipo="artigo">
			<AUTOR>CARVALHO, Diego Fiori de</AUTOR>
			<AUTOR>GOULARTE, R.</AUTOR>
			<TITULO>MP4Stego: Steganography in MPEG-4 Videos</TITULO>
			<TITULO-PUBLICACAO>International Journal of Advanced Media and Communication</TITULO-PUBLICACAO>
			<ANO>2009</ANO>
		</PUBLICACAO>
		<PUBLICACAO tipo="artigo">
			<AUTOR>MELLO, R. F.</AUTOR>
			<AUTOR>GOULARTE, R.</AUTOR>
			<AUTOR>Dodonov, Evgueni</AUTOR>
			<AUTOR>Yang, Laurence T.</AUTOR>
			<AUTOR>Park, Jong Hyuk</AUTOR>
			<AUTOR>Kim, Tai-hoon</AUTOR>
			<TITULO>On modeling and evaluating multicomputer transcoding architectures for live-video streams</TITULO>
			<TITULO-PUBLICACAO>Multimedia Tools and Applications</TITULO-PUBLICACAO>
			<ANO>2009</ANO>
		</PUBLICACAO>
		<PUBLICACAO tipo="artigo">
			<AUTOR>MANZATO, M. G.</AUTOR>
			<AUTOR>GOULARTE, R.</AUTOR>
			<TITULO>Peersommender: A peer-level annotation based approach for multimedia recommendation</TITULO>
			<TITULO-PUBLICACAO>Journal of Information and Data Management - JIDM</TITULO-PUBLICACAO>
			<ANO>2010</ANO>
		</PUBLICACAO>
		<PUBLICACAO tipo="artigo">
			<AUTOR>MANZATO, M. G.</AUTOR>
			<AUTOR>COIMBRA, D. B.</AUTOR>
			<AUTOR>GOULARTE, R.</AUTOR>
			<TITULO>An enhanced content selection mechanism for personalization of video news programmes</TITULO>
			<TITULO-PUBLICACAO>Multimedia Systems</TITULO-PUBLICACAO>
			<ANO>2011</ANO>
		</PUBLICACAO>
		<PUBLICACAO tipo="artigo">
			<AUTOR>LOPES, B.L.</AUTOR>
			<AUTOR>TROJAHN, T.</AUTOR>
			<AUTOR>GOULARTE, R.</AUTOR>
			<TITULO>Video Scene Detection by Multimodal Bag of Features</TITULO>
			<TITULO-PUBLICACAO>Journal of Information and Data Management - JIDM</TITULO-PUBLICACAO>
			<ANO>2014</ANO>
		</PUBLICACAO>
		<PUBLICACAO tipo="artigo">
			<AUTOR>SANTOS JUNIOR, E. B.</AUTOR>
			<AUTOR>TROJAHN, T.</AUTOR>
			<AUTOR>GOULARTE, R.</AUTOR>
			<TITULO>Evaluating the impact of demographic data on a hybrid recommender model</TITULO>
			<TITULO-PUBLICACAO>IADIS International Journal on WWWInternet</TITULO-PUBLICACAO>
			<ANO>2014</ANO>
		</PUBLICACAO>
		<PUBLICACAO tipo="artigo">
			<AUTOR>SANTOS JUNIOR, E. B.</AUTOR>
			<AUTOR>ZINGARELLI, MATHEUS R. U.</AUTOR>
			<AUTOR>SILVA, RODOLFO R.</AUTOR>
			<AUTOR>GOULARTE, R.</AUTOR>
			<TITULO>A new approach to spatial compression of stereoscopic videos (DOI: 10.1007/s11042-012-1300-0)</TITULO>
			<TITULO-PUBLICACAO>Multimedia Tools and Applications</TITULO-PUBLICACAO>
			<ANO>2014</ANO>
		</PUBLICACAO>
		<PUBLICACAO tipo="artigo">
			<AUTOR>MANZATO, M. G.</AUTOR>
			<AUTOR>SANTOS JUNIOR, E. B.</AUTOR>
			<AUTOR>GOULARTE, R.</AUTOR>
			<TITULO>Leveraging Hybrid Recommenders with Multifaceted Implicit Feedback</TITULO>
			<TITULO-PUBLICACAO>Journal of Universal Computer Science (Online)</TITULO-PUBLICACAO>
			<ANO>2015</ANO>
		</PUBLICACAO>
		<PUBLICACAO tipo="artigo">
			<AUTOR>VILLENA, JOHANA M. ROSAS</AUTOR>
			<AUTOR>RAMOS, BRUNO C.</AUTOR>
			<AUTOR>FORTES, R. P. M.</AUTOR>
			<AUTOR>GOULARTE, R.</AUTOR>
			<TITULO>An Accessible Video Player for Older People: Issues from a User Test</TITULO>
			<TITULO-PUBLICACAO>Procedia Computer Science</TITULO-PUBLICACAO>
			<ANO>2014</ANO>
